### ISSUE TITLE
uv-e-filesDownload - user, password

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#127]
I have one row, I fill user name and password and click "save". I got "Configuration problem exception".

![image](https://cloud.githubusercontent.com/assets/3341693/6320174/c8e15870-bad7-11e4-8afb-616ef2365334.png)

Exception: 
```
2015-02-22 21:16:40,331 [http-nio-8080-exec-5] ERROR cz.cuni.mff.xrg.odcs.frontend.gui.ViewComponent - Failed to load configuration for 74
eu.unifiedviews.dpu.config.DPUConfigException: Exception occured while loading configuration.
        at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownloadVaadinDialog.setConfiguration(FilesDownloadVaadinDialog.java:194) ~[na:na]
        at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownloadVaadinDialog.setConfiguration(FilesDownloadVaadinDialog.java:24) ~[na:na]
        at eu.unifiedviews.helpers.dpu.config.BaseConfigDialog.setConfig(BaseConfigDialog.java:80) ~[BaseConfigDialog.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPURecordWrap.loadConfigIntoDialog(DPURecordWrap.java:208) ~[DPURecordWrap.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPURecordWrap.configuredDialog(DPURecordWrap.java:108) ~[DPURecordWrap.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.configureDPUDialog(DPUViewImpl.java:901) [DPUViewImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.access$400(DPUViewImpl.java:48) [DPUViewImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$9.buttonClick(DPUViewImpl.java:488) [DPUViewImpl$9.class:na]
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [ListenerMethod.class:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [EventRouter.class:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [EventRouter.class:7.3.7]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) [AbstractClientConnector.class:7.3.7]
        at com.vaadin.ui.Button.fireClick(Button.java:393) [Button.class:7.3.7]
        at com.vaadin.ui.Button$1.click(Button.java:57) [Button$1.class:7.3.7]
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) [ServerRpcManager.class:7.3.7]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [ServerRpcManager.class:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:287) [ServerRpcHandler.class:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [ServerRpcHandler.class:7.3.7]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [UidlRequestHandler.class:7.3.7]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [SynchronizedRequestHandler.class:7.3.7]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [VaadinService.class:7.3.7]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [VaadinServlet.class:7.3.7]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [tomcat8-servlet-api-8.0.14.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: java.lang.IllegalArgumentException: Character a at position 0 is not a valid hexidecimal character
        at org.apache.commons.vfs2.util.DefaultCryptor.decode(DefaultCryptor.java:104) ~[na:na]
        at org.apache.commons.vfs2.util.DefaultCryptor.decrypt(DefaultCryptor.java:74) ~[na:na]
        at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownloadVaadinDialog.setConfiguration(FilesDownloadVaadinDialog.java:185) ~[na:na]
        ... 51 common frames omitted
```

**Comment by skodape** [comment]
If I then click to other DPU and back, then there is not a single row .. so I somehow "broke" the configuration.
