### ISSUE TITLE
E-FilesDownload fails to download file using HTTPS with invalid certificate

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#186]
Try to download https://www.isvz.cz/ReportingSuite/Explorer/Download/Data/XML/VVZ/2014 using E-FilesDownload. The web server does not have a valid certificate and the download fails with
```
Execution failed because: Exception occured while downloading files.eu.unifiedviews.dpu.DPUException: Exception occured while downloading files.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:193)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:128)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to HTTP server on "www.isvz.cz".
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:152)
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:50)
at org.apache.commons.vfs2.provider.http.HttpFileProvider.doCreateFileSystem(HttpFileProvider.java:83)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:103)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:81)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:65)
at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:693)
at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:621)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:125)
... 5 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:735)
at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:148)
... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
at sun.security.validator.Validator.validate(Validator.java:260)
at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
... 31 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
... 37 more
```

The expected behavior is to ignore invalid certificate and download anyway (maybe report an INFO level message).

Before this DPU I used <a href="http://stackoverflow.com/questions/12060250/ignore-ssl-certificate-errors-with-java">this workaround</a>.

**Comment by skrchnavy** [comment]
We shall be very careful with this requirement, as is also mentioned in the comment http://stackoverflow.com/a/12060890: _First, don't ignore certificate errors. Deal with them instead. Ignoring certificate errors opens the connection to potential MITM attacks. It's like turning off the buzzer in your smoke alarm because sometimes it makes a noise..._

For production it is not safe to allow such behaviour, there could be warning from security audit. Such certificates must be possible to install into system when admin of UV trust it.

**Comment by jakubklimek** [comment]
You are right, but rather then implementing certificate installation, I would add a checkbox with a warning sign that would enable ignoring certificates as this is a rather common situation.

If you would like to be highly secure by not allowing untrusted certificates, you could also disable plain HTTP, which is, of course, non-sense. In this case, I would trust the pipeline developer that he has seen the downloaded file before and knows that it is a case of a lazy or cheap webadmin rather than a security issue.

**Comment by skrchnavy** [comment]
Such checkbox shall be disabled per installation, so we could define a property like 'strict.security' and to have similar parameters displayed only when false.
For example in this DPU it could also disable usage of insecure protocols when user provides name and passwords.
In other DPUs there could be similar use cases.

**Comment by tomas-knap** [comment]
Solution: 
Let's start with a simple solution: Adding checkbox which allows E-FilesDownload to download also from HTTPS with failed certificate, if user decides so. By default, such checkbox is unchecked. 

In the future, we may use "strict.security"  if it shows up to be useful. 

@skrchnavy Please allocate.

**Comment by skrchnavy** [comment]
Be aware of usage of DPU in more strict environment, such change could cause refuse of using DPU.

**Comment by mkl-eea-sk** [comment]
Can this be solved by special DPU which handles all odds Jakub needs?

**Comment by skrchnavy** [comment]
#259 fix this issue
