### ISSUE TITLE
l-filesToVirtuoso: Non unique primary key on DB.DBA.LOAD_LIST

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#188]
I suspect that when multiple pipelines load to the same virtuoso instance at the same time, this exception happens:
```
Error executing query

Stack trace:
virtuoso.jdbc4.VirtuosoException SR197: Non unique primary key on DB.DBA.LOAD_LIST.
   at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:344)
   at virtuoso.jdbc4.VirtuosoResultSet.<init>(VirtuosoResultSet.java:58)
   at virtuoso.jdbc4.VirtuosoStatement.sendQuery(VirtuosoStatement.java:138)
   at virtuoso.jdbc4.VirtuosoStatement.executeQuery(VirtuosoStatement.java:230)
   at eu.unifiedviews.plugins.loader.filestovirtuoso.VirtuosoLoader.innerExecute(VirtuosoLoader.java:252)
   at eu.unifiedviews.helpers.cuni.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
```

Is this DPU tested when loading in parallel from multiple pipelines?

**Comment by tomas-knap** [comment]
To be tested.
