### ISSUE TITLE
l-rdfToVirtuoso cannot be built due to non-resolvable parent POM

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#219]
Same issue as [this one](https://github.com/OpenDataNode/UVPlugin-rdfToVirtuosoAndCkan/issues/2).

Trying `mvn -e install` on 4ff15bd466510d2fb7994b4e12e2d2ecc9f0ff1d from the feature/l-rdfToVirtuoso branch results in the following error:

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM: Failure to find eu.unifiedviews:uv-pom-dpu:pom:2.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:405)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:663)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:654)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:243)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project eu.unifiedviews.plugins:uv-l-rdfToVirtuoso:1.0.0-SNAPSHOT (/Users/mynarzjindrich/Dev/UnifiedViews/Plugins/l-rdfToVirtuoso/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find eu.unifiedviews:uv-pom-dpu:pom:2.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 10 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Failure to find eu.unifiedviews:uv-pom-dpu:pom:2.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:175)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:224)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:903)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:755)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:309)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:452)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:421)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:385)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:663)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:654)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:243)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find eu.unifiedviews:uv-pom-dpu:pom:2.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:295)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:171)
	... 22 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find eu.unifiedviews:uv-pom-dpu:pom:2.0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:232)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:599)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:518)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
	... 26 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by skrchnavy** [comment]
fixed
