### ISSUE TITLE
uv-l-filesToCkan : Could not obtain dataset from 

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Plugins#234]
When user runs pipeline uv-l-filesToCkan for the first time then uv-l-filesToCkan fails. However, when user runs pipeline for the second time then it works fine.

version: UV_Plugins_v2.0.1

uv.log:
```
Execution failed because: Could not obtain dataset from CKAN.eu.unifiedviews.dpu.DPUException: Could not obtain dataset from CKAN. at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181) at eu.unifiedviews.plugins.loader.filestockan.FilesToCkan.innerExecute(FilesToCkan.java:197) at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) at java.lang.Thread.run(Thread.java:745)
```

ckan - internalcatalog
```
[Fri May 29 13:55:23 2015] [error] 2015-05-29 13:55:23,084 ERROR [ckanext] Error sending request to http://127.0.0.1:28080/master/api/1/pipelines: {"error":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException\\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \\"ppl_model_name_key\\"\\n  Detail: Key (name)=(dataset) already exists.\\nError Code: 0\\nCall: INSERT INTO ppl_model (ID, DESCRIPTION, last_change, NAME, visibility, organization_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\\n\\tbind => [2, , 2015-05-29 13:55:22.794, dataset, 0, null, 1]\\nQuery: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@2a9)"}
[Fri May 29 13:55:23 2015] [error] Traceback (most recent call last):
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/controllers/pipeline.py", line 351, in create_pipe_manually
[Fri May 29 13:55:23 2015] [error]     new_pipe = uv_api.create_pipeline(name, description, user_id, org_id)
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/pipeline/uv_helper.py", line 98, in create_pipeline
[Fri May 29 13:55:23 2015] [error]     return self._send_request_with_data(uv_url, json.dumps(data))
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/pipeline/uv_helper.py", line 72, in _send_request_with_data
[Fri May 29 13:55:23 2015] [error]     raise Exception("Error sending request to {0}: {1}".format(uv_url, response.text))
[Fri May 29 13:55:23 2015] [error] Exception: Error sending request to http://127.0.0.1:28080/master/api/1/pipelines: {"error":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException\\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \\"ppl_model_name_key\\"\\n  Detail: Key (name)=(dataset) already exists.\\nError Code: 0\\nCall: INSERT INTO ppl_model (ID, DESCRIPTION, last_change, NAME, visibility, organization_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\\n\\tbind => [2, , 2015-05-29 13:55:22.794, dataset, 0, null, 1]\\nQuery: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@2a9)"}
```

**Comment by skrchnavy** [comment]
@Jan-Marcek please write the issue in proper repository: https://github.com/OpenDataNode/UVPlugin-filesToCKAN

**Comment by Jan-Marcek** [comment]
moved https://github.com/OpenDataNode/UVPlugin-filesToCKAN/issues/7
