### ISSUE TITLE
l-filesUpload: improve documentation of DPU with examples of configuration

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#240]
Validation of the DPU's configuration fails if user is filled in
---

When you fill in user and password in l-filesUpload (version 2.0.1 shipped in ODN 1.0.2), the DPU's configuration cannot be saved because its validation fails with the following error: `Failed to save configuration. Reason: URI is invalid.`

Using the same URI without username and password the validation passes.

When I try to load the most recent develop version of l-filesUpload (dbedf40c22a179fcbcabfa0b77a377fe738ba990) into the UnifiedViews in ODN 1.0.2, the load fails with the following error:

```
Can't load instance from new bundle. Exception: org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-l-filesUpload_2.1.0.SNAPSHOT [41]" could not be resolved. Reason: Missing Constraint: Import-Package: eu.unifiedviews.dataunit; version="[2.1.0,3.0.0)"
```

**Comment by mkl-eea-sk** [comment]
I can only reproduce this issue when URI in dialog is
- invalid
- valid without host part

These two cases I guess, are invalid either. Trying to set credentials for logging in, but where should DPU connect when there is no host part in URI? Maybe the message may be altered, but the behavior in correct (latest develop version).

Or maybe I am missing something, what are the precise values you are trying to enter?

**Comment by jindrichmynarz** [comment]
I guess the problem is due to my understanding of the expected format of the URI. As @mkl-eea-sk writes, while <file://localhost/var/cache/virtuoso/upload> is correct, simple file path `/var/cache/virtuoso/upload` is not. This is not something that I have known. I find it quite unfriendly that a simple file path cannot be used. To certain degree this could be fixed by documentation. However, the documentation does not help here. In fact, the [about document](https://github.com/UnifiedViews/Plugins/blob/develop/l-filesUpload/doc/About.md) talks about "Destination directory absolute path" field, while the DPU contains "URI" field (checked with the latest develop version, 99b8c08b98b85611b2f9ae36a3668281390614e3). Therefore, one of the steps to solving this issue is to improve the documentation. In particular, doing this is crucial if the DPU will require the `file://localhost/var/cache/virtuoso/upload` format of URI to a file. However, I would suggest to also think how to make this easier for the user by e.g., allowing to use plain file path.

The second thing is that I have not managed to get the most recent version of the DPU to work with the `file://localhost/var/cache/virtuoso/upload` URI format. Upon running a pipeline with this URI, the following error is thrown:

```
Execution failed because: Operation failed.eu.unifiedviews.dpu.DPUException: Operation failed.
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.checkFailState(FaultTolerance.java:260)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:274)
at eu.unifiedviews.plugins.loader.filesupload.FilesUpload.innerExecute(FilesUpload.java:136)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:133)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not copy "file:///opt/var/lib/unifiedviews/working/exec_103/storage/dpu_247/0/contaminat7134991512078681484" to "file:///localhost/var/cache/virtuoso/upload/contaminated_sites.ttl".
at org.apache.commons.vfs2.provider.AbstractFileObject.copyFrom(AbstractFileObject.java:1062)
at eu.unifiedviews.plugins.loader.filesupload.FilesUpload$1.action(FilesUpload.java:146)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:271)
... 6 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not create folder "file:///localhost".
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:999)
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:982)
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:982)
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:982)
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:982)
at org.apache.commons.vfs2.provider.AbstractFileObject.getOutputStream(AbstractFileObject.java:1424)
at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:461)
at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:441)
at org.apache.commons.vfs2.FileUtil.copyContent(FileUtil.java:111)
at org.apache.commons.vfs2.provider.AbstractFileObject.copyFrom(AbstractFileObject.java:1053)
... 8 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not create directory "/localhost".
at org.apache.commons.vfs2.provider.local.LocalFile.doCreateFolder(LocalFile.java:153)
at org.apache.commons.vfs2.provider.AbstractFileObject.createFolder(AbstractFileObject.java:988)
... 17 more
```

I have checked that the path is writable by the provided user, so I assume this must be an issue of the DPU.

**Comment by mkl-eea-sk** [comment]
Of course you cannot use file:///localhost/etc to locate files on your 
computer.
You can use
```
file:///c:/something
```
or
```
/c:/something
```
or
```
/var/log/something
```
the absolute Path works. But not with name and password. I don't 
understand your requirement:
1. I want to download file from absolute path on my system
2. I have to provide name and password to access file

it seems to me, that these two statements can not be true at the same time.
Or are they? How? I was asking you, please provide me what exactly are 
you entering to dialog...

**Comment by skrchnavy** [comment]
I agree that we have to improve documentation of L-filesUpload to provide good examples and also possible troubles.

Anyway user friendly dialog shall be provided to avoid confusion to be able to easily configure upload to:
* local file system
* remote file system using predefined set of protocols
And also to have advanced mode for free form as is now.

**Comment by jindrichmynarz** [comment]
@mkl-eea-sk: Here's a concrete example. I want to upload a file to `/var/cache/virtuoso/upload`, which is owned by the user `uploader` that is created by default by ODN (see [here](https://utopia.sk/wiki/display/ODN/Open+Data+Node+v1.1.0#OpenDataNodev1.1.0-Defaultusers)). What I should fill in l-filesUpload?

If I fill in the following, the URI is reported as invalid:

URI:  /var/cache/virtuoso/upload
Username: uploader
Password: uploader

If I fill in the following, the above-mentioned error is thrown during the pipeline execution:

URI:  file://localhost/var/cache/virtuoso/upload
Username: uploader
Password: uploader

**Comment by mkl-eea-sk** [comment]
Fill
/var/cache/virtuoso/upload
and leave username and pasword empty

**Comment by jindrichmynarz** [comment]
Do I understand correctly that l-filesUpload is *implicitly* run under the user `uploader`? If that is the case, then it should be documented, so that other users are not as confused as I am.

**Comment by jindrichmynarz** [comment]
Alternatively, what if I want to upload to a directory not owned by the `uploader` user? Is that supported by the DPU?

**Comment by mkl-eea-sk** [comment]
I do not know under which user it runs - ask @Jan-Marcek. Nevermind -- give it a try. I am suspicious. It may be bug in ODN .deb packaging (UV running under unifiedviews user/or tomcat7 user, folder owner by uploader).

If you want to log in by username and password you have to user protocol which support credentials, which definitely local filesystem access from Java is NOT (VFS2 uses java.io.File for local filesystem resolves). So entering user/pass for local files in filesUpload does not make any sense. You cannot suid your UV process in DPU....

Give me feedback if proposed solution works please.

**Comment by jindrichmynarz** [comment]
When I use `/var/cache/virtuoso/upload` as URL and no username and password, the pipeline works. The file is uploaded as owned by the user `unifiedviews` from the group `uploaders`. It turns out that every user from this group is allowed to write into that directory.

I think we can resolve this issue by improving the documentation of this DPU. In particular, the expected URL formats should be described.

**Comment by skrchnavy** [comment]
agreed to imrpove About.md

**Comment by jindrichmynarz** [comment]
I think we agreed that About.md needs to be improved. Please close this with a commit message that improves the documentation of the DPU.

**Comment by skrchnavy** [comment]
@mbl-eea-sk to add examples how to configure DPU for typical cases:
* upload files to local FS
* upload files via scp
* upload files via http/https
* zip files to local FS

Localisation to slovak also expected

**Comment by mbl-eea-sk** [comment]
Should this be done for entire Plugins project (by creating analogic About.md file) or just for separate DPUs l-filesUpload and t-zipper?

**Comment by skrchnavy** [comment]
This shall be done in About.md (and language variants) of l-filesUpload DPU.
