### ISSUE TITLE
e-filesDownload: javax.net.ssl.SSLException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#306]
It seems that e-filesDownload has an issue with downloading from HTTPS. For example, when I want to download <https://www.sk-nic.sk/documents/domeny.txt.gz>, the `javax.net.ssl.SSLException: Received fatal alert: protocol_version` is raised:

```
Execution failed because: Exception occured while downloading files.eu.unifiedviews.dpu.DPUException: Exception occured while downloading files.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:212)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:160)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:133)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to HTTP server on "www.sk-nic.sk".
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:152)
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:50)
at org.apache.commons.vfs2.provider.http.HttpFileProvider.doCreateFileSystem(HttpFileProvider.java:83)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:103)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:81)
at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:65)
at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:693)
at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:621)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:157)
... 5 more
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:709)
at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.apache.commons.vfs2.provider.http.HttpClientFactory.createConnection(HttpClientFactory.java:148)
... 13 more
```

Context: Tested with the latest commit from the develop branch (2dd97992039e1f1898f626e2e9cb5eb03c9d7ad6).

**Comment by mkl-eea-sk** [comment]
http://stackoverflow.com/a/22432494 what JDK and version you have?

**Comment by jindrichmynarz** [comment]
```$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by mkl-eea-sk** [comment]
https://bugs.openjdk.java.net/browse/JDK-8087170

**Comment by mkl-eea-sk** [comment]
As the Jira is readonly for public, I have sent an email to help@openjdk.java.net, quoting:
```
Subject:Commenting on https://bugs.openjdk.java.net/browse/JDK-8087170
Body:
Hi,
as the access to JIRA is read-only, I have to write you an email to post a comment on a specific bug.
Ad. https://bugs.openjdk.java.net/browse/JDK-8087170
Comment text:
I was able to reproduce and a I am giving more detailed info here https://github.com/UnifiedViews/Plugins/issues/306#issuecomment-132494577
with versions of JDK and new site which triggers the error (for the moment).
```
I do not know, what more can I do. Testing with openssl s_client -connect www.sk-nic.sk:443 works fine.

**Comment by mbl-eea-sk** [comment]
The test above passed on Windows 7 Professional x64 with Java configuration:
```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```
with response:
```
HttpResponseProxy{HTTP/1.1 200 OK [Server: SK-NIC Server, Set-Cookie: JSESSIONID=2E243962A76C8E2A651875F0D252A3DD; Path=/; Secure; HttpOnly, Accept-Ranges: bytes, ETag: W/"5337638-1439952072000", Last-Modified: Wed, 19 Aug 2015 02:41:12 GMT, Content-Type: application/x-gzip, Content-Length: 5337638, Date: Wed, 19 Aug 2015 09:16:08 GMT, Strict-Transport-Security: max-age=31536000; includeSubDomains] ResponseEntityProxy{[Content-Type: application/x-gzip,Content-Length: 5337638,Chunked: false]}}
```

**Comment by jindrichmynarz** [comment]
Would updating JDK help? If that is the case, then maybe @Jan-Marcek can say if doing so is possible in the ODN.

**Comment by mkl-eea-sk** [comment]
I do not know, I have sent an email to openjdk as I had written before. We should ask them. At least we see, that the problem is related to what JDK user is using. That may be indication, that in fact, the problem is not in our code.

**Comment by pgo-eea-sk** [comment]
The test above passed on Windows 7 Professional x64 with Java configuration:
```
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```
with response:
```
javax.net.ssl.SSLException: Received fatal alert: protocol_version
```

**Comment by mkl-eea-sk** [comment]
Re: https://github.com/UnifiedViews/Plugins/issues/306#issuecomment-132535438 Probably, update to java 8 will help

**Comment by mkl-eea-sk** [comment]
Finally, I have managed to make a workaround for java 7. Pull request https://github.com/UnifiedViews/Plugins/pull/308
