### ISSUE TITLE
t-xslt does not support xsl:result-document

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#322]
t-xslt currently does not support [`xsl:result-document`](http://www.w3.org/TR/xslt20/#element-result-document). If a stylesheet containing this instruction is used, an uninformative exception such as the following one is raised:

```
Execution failed because: Operation failed.eu.unifiedviews.dpu.DPUException: Operation failed.
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.checkFailState(FaultTolerance.java:244)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:258)
at eu.unifiedviews.plugins.transformer.xslt.Xslt.innerExecute(Xslt.java:189)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/opt/var/lib/unifiedviews/working/exec_458/storage/dpu_1109/1/0. File must exists prior being added.
at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:114)
at eu.unifiedviews.plugins.transformer.xslt.Xslt$5.action(Xslt.java:194)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:255)
... 6 more
```

Context: tested on t-xslt in ODN 1.1.0.

**Comment by tomas-knap** [comment]
@jindrichmynarz Is this something you need to have fixed till 2.2.0 release (in a week)?

**Comment by jindrichmynarz** [comment]
The CPV pipeline had to be simplified because of this issue. Other than that, I think I can mostly work around it.

**Comment by skrchnavy** [comment]
Based on documentation http://www.saxonica.com/html/documentation/xsl-elements/result-document.html  shall support `xsl:result-document`. There could be a bug in implementation.
Some bugs were solved in version 9.6.0.5 and 9.6.0.6 (in DPU there is currently used 9.6.0.4).
See http://sourceforge.net/projects/saxon/files/Saxon-HE/9.6/

**Comment by jindrichmynarz** [comment]
Yes, Saxon supports it. Simple test case:

Let's have a source XML document:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root/>
```

And a simple XSLT that uses `result-document`:

```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="2.0">
    
    <xsl:output encoding="UTF-8" method="text" />
    
    <xsl:template match="/">
        <xsl:result-document href="result.txt">HEY, THIS IS A TEST!</xsl:result-document>
    </xsl:template>
</xsl:stylesheet>
```

Running the transformation with Saxon-HE 9.5.1.6J produces the file `result.txt` with the expected content (`HEY, THIS IS A TEST!`).

When I run the same transformation on the same input in UnifiedViews using t-xslt (compiled from latest develop, 0059daa20b6ad6a5daf4b83f5e21ca80bbab0de2), fails with this exception:

```
2015-09-02 15:41:56,534 [dpu: uv-t-xslt] ERROR exec:648 dpu:797 c.c.m.x.o.b.pipeline.event.PipelineFailedEvent - Pipeline failed on DPU 'uv-t-xslt' because of the exception
eu.unifiedviews.dpu.DPUException: Operation failed.
	at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.checkFailState(FaultTolerance.java:241) ~[uv-dpu-helpers-2.1.2.jar:na]
	at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:255) ~[uv-dpu-helpers-2.1.2.jar:na]
	at cz.cuni.mff.xrg.uv.transformer.xslt.Xslt.innerExecute(Xslt.java:188) ~[na:na]
	at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) ~[uv-dpu-helpers-2.1.2.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:248) [backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:386) [backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468) [backend-2.2.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: eu.unifiedviews.dataunit.DataUnitException: File does not exist: file:/Users/mynarzjindrich/Dev/UnifiedViews/app/Core/backend/working/exec_648/storage/dpu_797/1/0. File must exists prior being added.
	at eu.unifiedviews.dataunit.files.impl.LocalFSFilesDataUnit.addExistingFile(LocalFSFilesDataUnit.java:130) ~[dataunit-file-impl-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.uv.transformer.xslt.Xslt$5.action(Xslt.java:193) ~[na:na]
	at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:252) ~[uv-dpu-helpers-2.1.2.jar:na]
	... 6 common frames omitted
```

Desirable outcome: a FilesDataUnit with the `result.txt` file containing the result of the transformation.

**Comment by skrchnavy** [comment]
are you able to find `result.txt` file on your file system after DPU run? where it is located? Above error is probably caused by missing file when adding into output (file is not in the location where it is expected).
http://www.saxonica.com/html/documentation/xsl-elements/result-document.html explain how href is processed and this shall be followed in DPU to integrate UV and saxon.

**Comment by jindrichmynarz** [comment]
Yes, actually I'm able to find the `result.txt` file if I run the pipeline in the debug mode. The file is located in `{general.workingdir}/{execution ID}/storage/{DPU ID}/1/result.txt`.

**Comment by skrchnavy** [comment]
(for the record)

based on error it is expected that file has name: `{general.workingdir}/{execution ID}/storage/{DPU ID}/1/{fileIndex}` 

Output file is requested to be created with name `fileIndex` see https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v2.1.3/t-xslt/src/main/java/eu/unifiedviews/plugins/transformer/xslt/Xslt.java#L117
and xsl:result-document renames it (if I understood).
and adding into output it is expected with requested name
https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v2.1.3/t-xslt/src/main/java/eu/unifiedviews/plugins/transformer/xslt/Xslt.java#L194
