### ISSUE TITLE
l-filesUpload: failed to merge contexts

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#327]
l-filesUpload (compiled from latest develop branch, 0059daa20b6ad6a5daf4b83f5e21ca80bbab0de2) fails to merge contexts when provided with multiple inputs. According to the error the DPU is provided with duplicate symbolic names, so the question is if this is:

a) A bug of l-filesUpload that should be able to merge inputs anyway
b) A bug of DPUs providing data to l-filesUpload, which should not mint duplicate symbolic names

```
2015-09-02 07:33:00,901 [dpu: uv-l-filesUpload] ERROR exec:628 dpu:772 e.u.c.dataunit.AbstractWritableMetadataDataUnit - Duplicate entry found for symbolic name: 85234e7b035c612cf2fedf199691941835d8d4ce
2015-09-02 07:33:00,903 [dpu: uv-l-filesUpload] ERROR exec:628 dpu:772 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUEvent - Pre-executor 'cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorContextPreparator' failed for DPU 'uv-l-filesUpload' with message: 'Failed to merge contexts.'
cz.cuni.mff.xrg.odcs.backend.context.ContextException: Can't merge data units.
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merger(ContextMerger.java:173) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merge(ContextMerger.java:50) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.merge(ContextFacade.java:118) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorContextPreparator.execute(DPUPreExecutorContextPreparator.java:107) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorBase.preAction(DPUPreExecutorBase.java:61) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executePreExecutors(DPUExecutor.java:209) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:339) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: eu.unifiedviews.dataunit.DataUnitException: Duplicate symbolic names found, see logs for more details.
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit$5.execute(AbstractWritableMetadataDataUnit.java:489) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:93) ~[commons-app-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:57) ~[commons-app-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.checkForDuplicitEntries(AbstractWritableMetadataDataUnit.java:454) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.merge(AbstractWritableMetadataDataUnit.java:276) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merger(ContextMerger.java:168) ~[backend-2.2.0-SNAPSHOT.jar:na]
	... 8 common frames omitted
```

**Comment by jindrichmynarz** [comment]
t-filesMerger also cannot merge inputs with duplicate symbolic names:

```
2015-09-02 07:45:04,088 [dpu: uv-t-filesMerger] ERROR exec:629 dpu:781 e.u.c.dataunit.AbstractWritableMetadataDataUnit - Duplicate entry found for symbolic name: 85234e7b035c612cf2fedf199691941835d8d4ce
2015-09-02 07:45:04,090 [dpu: uv-t-filesMerger] ERROR exec:629 dpu:781 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUEvent - Pre-executor 'cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorContextPreparator' failed for DPU 'uv-t-filesMerger' with message: 'Failed to merge contexts.'
cz.cuni.mff.xrg.odcs.backend.context.ContextException: Can't merge data units.
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merger(ContextMerger.java:173) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merge(ContextMerger.java:50) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.merge(ContextFacade.java:118) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorContextPreparator.execute(DPUPreExecutorContextPreparator.java:107) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.DPUPreExecutorBase.preAction(DPUPreExecutorBase.java:61) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executePreExecutors(DPUExecutor.java:209) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:339) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468) ~[backend-2.2.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: eu.unifiedviews.dataunit.DataUnitException: Duplicate symbolic names found, see logs for more details.
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit$5.execute(AbstractWritableMetadataDataUnit.java:489) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:93) ~[commons-app-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:57) ~[commons-app-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.checkForDuplicitEntries(AbstractWritableMetadataDataUnit.java:454) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.merge(AbstractWritableMetadataDataUnit.java:276) ~[dataunit-2.2.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.backend.context.ContextMerger.merger(ContextMerger.java:168) ~[backend-2.2.0-SNAPSHOT.jar:na]
	... 8 common frames omitted
```

Is the problem in DPUs generating duplicate symbolic names?

**Comment by skrchnavy** [comment]
this is a feature. filesUpload shall upload files that are unique, so files rename DPU shall be used to solve duplicates.
On the other hand, better error report shall be implemented to inform user about solution. Also documentation shall contain such information.

**Comment by jindrichmynarz** [comment]
Fine. Then it seems there is still an issue with e-filesDownload that produces duplicate symbolic names, which was allegedly fixed in #274.

**Comment by skrchnavy** [comment]
Are you able to reproduce it with released version?

**Comment by jindrichmynarz** [comment]
Strange, I'm unable to reproduce this issue. Closing it for now.
