### ISSUE TITLE
e-executeShellScript: Symlinked scripts are not recognized

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#330]
The DPU does not recognize symbolic links. For example, I have a script symlinked from `/usr/bin/uvunzip`. If I just pass `uvunzip` as the script name to the DPU, the following error is raised:

```
Execution failed because: Given script doesnt exixst.eu.unifiedviews.dpu.DPUException: Given script doesnt exixst.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181)
at eu.comsode.unifiedviews.plugins.extractor.executeshellscript.ExecuteShellScript.innerExecute(ExecuteShellScript.java:64)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
```

If I provide the absolute path to the script, then it works.

Additionally, @skrchnavy writes that "script location shall be configurable with default in UV workspace".

(moved from OpenDataNode/UVPlugin-executeShellScript#2 )

**Comment by pgo-eea-sk** [comment]
Resolved by commit https://github.com/UnifiedViews/Plugins/commit/6b920bd45c0523e29c059577303121e3c12c750e
