### ISSUE TITLE
e-filesDownload 2.1.5: Could not determine the type of file (working in 2.0.1)

### ISSUE THREAD

**Issue by nvdk** [UnifiedViews/Plugins#382]
Since upgrading to unified-views 2.3 some of our old pipelines no longer work, specifically those that download over ssl (don't know if that's related). 

Previously we were using e-filesDownload version 2.0.1
Currently we are using e-filesDownload version 2.1.5

java version is OpenJDK Runtime Environment (build 1.8.0_72-internal-b15, 64bit)

Example url: https://qa.stad.gent/opendata/export/nieuws?from=2016-04-08T15:58:42+02:00

Stack trace:

```
Execution failed because: Exception occured while downloading files.eu.unifiedviews.dpu.DPUException: Exception occured while downloading files.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:212)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:162)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:133)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:248)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:386)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not determine the type of file "https://qa.stad.gent/opendata/export/nieuws?from=2016-04-08T15:58:42+02:00".
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:505)
at org.apache.commons.vfs2.provider.AbstractFileObject.exists(AbstractFileObject.java:477)
at org.apache.commons.vfs2.provider.AbstractFileObject.findFiles(AbstractFileObject.java:1192)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.innerExecute(FilesDownload.java:160)
... 5 more
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:170)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at sun.security.ssl.InputRecord.read(InputRecord.java:503)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.apache.commons.vfs2.provider.http.HttpFileObject.doGetType(HttpFileObject.java:80)
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:496)
... 8 more
```

**Comment by nvdk** [comment]
To elaborate, I could access and retrieve the files with wget from the server and had the same issue on oracle jdk 1.8. I resolved it by reverting this commit: https://github.com/UnifiedViews/Plugins/commit/81ce112406851c9c254355d62c83ce1364023ac9#diff-7c3c7d7007f9ff95403a7458b1ce9bb9

eg
```
git revert 81ce112406851c9c254355d62c83ce1364023ac
cd e-filesDownload
mvn package
```

**Comment by nvdk** [comment]
It seems I was wrong, what "resolved" my issue is the wget command I tried first. The actual issue seems to be the domain name is not resolved correctly by the java client.
