### ISSUE TITLE
T-rdf2files - DPUConfigException

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#77]
There are four t-sparql DPUs outputting data to one t-rdf2files DPU. All the t-sparql DPUs has different output symbolic name. Even thouugh, the following error occurs in t-rdf2files: 

UV 1.4.0, the pipeline available at: http://odcs.xrg.cz:8080/uv/#!PipelineEdit/11

Pre-executor 'cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator' failed for DPU 'T-RdfToFiles' with message: 'Failed to configure DPU.'

Stack trace:
eu.unifiedviews.dpu.config.DPUConfigException com.thoughtworks.xstream.converters.ConversionException: -1 : -1
---- Debugging information ----
message             : -1
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : -1
class               : java.util.Arrays$ArrayList
required-type       : java.util.Arrays$ArrayList
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /Configuration/graphToFileInfo
line number         : 11
class[1]            : eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig_V1
version             : not available
-------------------------------
   at eu.unifiedviews.helpers.dpu.config.ConfigWrap.deserialize(ConfigWrap.java:151)
   at eu.unifiedviews.helpers.dpu.config.ConfigurableBase.configure(ConfigurableBase.java:43)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator.preAction(Configurator.java:67)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executePreExecutors(DPUExecutor.java:192)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:322)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:451)
   at java.lang.Thread.run(Thread.java:745)
com.thoughtworks.xstream.converters.ConversionException -1 : -1
---- Debugging information ----
message             : -1
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : -1
class               : java.util.Arrays$ArrayList
required-type       : java.util.Arrays$ArrayList
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /Configuration/graphToFileInfo
line number         : 11
class[1]            : eu.unifiedviews.plugins.transformer.rdftofiles.RdfToFilesConfig_V1
version             : not available
-------------------------------
   ... 6 common frames omitted   at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
   at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
   at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
   at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
   at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
   at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
   at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1156)
   at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1128)
   at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1822)
   at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:120)
   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
   at eu.unifiedviews.helpers.dpu.config.ConfigWrap.deserialize(ConfigWrap.java:144)
   at eu.unifiedviews.helpers.dpu.config.ConfigurableBase.configure(ConfigurableBase.java:43)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator.preAction(Configurator.java:67)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executePreExecutors(DPUExecutor.java:192)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:322)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:451)
   at java.lang.Thread.run(Thread.java:745)
java.lang.ArrayIndexOutOfBoundsException -1
   ... 23 common frames omitted   at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1822)
   at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:120)
   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
   at eu.unifiedviews.helpers.dpu.config.ConfigWrap.deserialize(ConfigWrap.java:144)
   at eu.unifiedviews.helpers.dpu.config.ConfigurableBase.configure(ConfigurableBase.java:43)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.impl.Configurator.preAction(Configurator.java:67)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executePreExecutors(DPUExecutor.java:192)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:322)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:451)
   at java.lang.Thread.run(Thread.java:745)

**Comment by tomas-knap** [comment]
Cannot reproduce
